### ISSUE TITLE
Get an esdoc setup going

### ISSUE THREAD

**Issue by connor4312** [NaturalNode/node-sylvester#8]
Tracking for myself

**Comment by Hugo-ter-Doest** [comment]
I removed the Github action for Github Pages because you don't need an action for that. If you commit to the gh-pages branch it triggers publication to https://naturalnode.github.io/node-sylvester/

**Comment by Hugo-ter-Doest** [comment]
And restored the documentation workflow using https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by Hugo-ter-Doest** [comment]
I restored the documentation workflow.
- Updated to https://github.com/peaceiris/actions-gh-pagesv3
- Updated the syntax `env` in gh-pages.yml to `uses`
- Placed new public/private deploy keys in the repo.
Should work fine now.
